# Configure port
server:
  port: 8088

# Configure input file size check (this checks first in the code) and Connect DB
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: i18n/lang
    encoding: UTF-8
    default-locale: en
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0


# Create variable environment of api request
api:
  base:
    path: /api/v1

# Config JWT
jwt:
  expiration: 2592000 # 30 days
  secretKey: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  expiration-refresh-token: 5184000 # 60 days

#logging.level.org.springframework.security: DEBUG
logging:
  level:
    org:
      springframework:
        security: DEBUG

#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health, info"

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
